In [1]:
#Defining a list of 10 students ages
ages = [19,22,19,24,20,25,26,24,25,24]
ages

[19, 22, 19, 24, 20, 25, 26, 24, 25, 24]

In [2]:
#Sorting the list
ages.sort()

In [3]:
ages

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]

In [4]:
#Finding minimum of age
Minimum = min(ages)
Minimum

19

In [5]:
#Finding Maximum of age
Maximum = max(ages)
Maximum

26

In [6]:
#Adding Min and Max age again to the list ages
ages.append(Minimum)
ages.append(Maximum)
ages

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]

In [7]:
#Median Age 
L = len(ages) #Calculating Length of the list ages
L

12

In [8]:
#No of values in a list are even then median will be average of the two mid values of a list
A = int(L/2 -1) #A be the predecessor to the mid value in a list because list Index starts at 0
B = int(L/2) #B be the mid value in a list at Index 6
Median = (ages[A]+ages[B])/2
Median

24.0

In [9]:
#Average of List ages
S = sum(ages) #S be the Sum of all ages in a list ages
L = len(ages) #L be the length of the list
Average = S/L #Average can be calculated by sum of the values divided by Total no of Values in a list
Average

22.75

In [10]:
#Finding range of the ages
Maximum = max(ages)
Minimum = min(ages)
Range = Maximum - Minimum #Range means difference between maximum and minimum values in a list
Range

7

In [11]:
#QUESTION 2

In [12]:
#Creating a Empty Dictionary
Dog = {}
Dog

{}

In [13]:
#Appending values to a Dog Dictionary
Dog.update({"name" :"ABC", "color" : "Yellow", "breed" :"DEF", "legs" : 4, "age" : 15})
Dog

{'name': 'ABC', 'color': 'Yellow', 'breed': 'DEF', 'legs': 4, 'age': 15}

In [14]:
#Creating a Student Dictionary
Student = {"first_name" : "", "last_name" : "","gender": "", "age": "", "marital status": "", "skills":[], "country": "", "city":"", "address": ""}
Student

{'first_name': '',
 'last_name': '',
 'gender': '',
 'age': '',
 'marital status': '',
 'skills': [],
 'country': '',
 'city': '',
 'address': ''}

In [15]:
#Length of Student Dictionary
len(Student)

9

In [16]:
#Print values of Skills
S = Student['skills']
S

[]

In [17]:
type(S)

list

In [18]:
#Modifying skill values
Student["skills"].append('Python')
Student["skills"].append('ML')
Student['skills']

['Python', 'ML']

In [19]:
Student

{'first_name': '',
 'last_name': '',
 'gender': '',
 'age': '',
 'marital status': '',
 'skills': ['Python', 'ML'],
 'country': '',
 'city': '',
 'address': ''}

In [20]:
#Printing keys of Student Dictionary
Student.keys()

dict_keys(['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'country', 'city', 'address'])

In [21]:
#Printing keys of Student Dictionary as list
list(Student.keys())

['first_name',
 'last_name',
 'gender',
 'age',
 'marital status',
 'skills',
 'country',
 'city',
 'address']

In [22]:
#Printing values of Student Dictionary as list
list(Student.values())

['', '', '', '', '', ['Python', 'ML'], '', '', '']

In [23]:
#QUESTION 3

In [24]:
#Creating a Sisters and Brothers tuples
Sisters = ('Pooja','Shruti','Samyuktha','kriti')
Brothers = ('Mahesh','Vijay','Akhil','Balakrishna')

In [25]:
Sisters

('Pooja', 'Shruti', 'Samyuktha', 'kriti')

In [26]:
Brothers

('Mahesh', 'Vijay', 'Akhil', 'Balakrishna')

In [27]:
#Concatenating Sisters and Brothers tuples into a one tuple name it as siblings
Siblings = Brothers + Sisters
Siblings

('Mahesh',
 'Vijay',
 'Akhil',
 'Balakrishna',
 'Pooja',
 'Shruti',
 'Samyuktha',
 'kriti')

In [28]:
#Length of Sibilings tuple
len(Siblings)

8

In [29]:
#Modifying Siblings Tuple
Siblings.append('Krishna','Indiramma')

AttributeError: 'tuple' object has no attribute 'append'

In [30]:
#As tuples are unchangables directly, but we can update the tuple by converting tuples into a list
Change_tuple = list(Siblings) #converting tuple into a list
Change_tuple


['Mahesh',
 'Vijay',
 'Akhil',
 'Balakrishna',
 'Pooja',
 'Shruti',
 'Samyuktha',
 'kriti']

In [31]:
Change_tuple.extend(['Krishna','Indira'])
Change_tuple

['Mahesh',
 'Vijay',
 'Akhil',
 'Balakrishna',
 'Pooja',
 'Shruti',
 'Samyuktha',
 'kriti',
 'Krishna',
 'Indira']

In [32]:
family_members = tuple(Change_tuple)
family_members

('Mahesh',
 'Vijay',
 'Akhil',
 'Balakrishna',
 'Pooja',
 'Shruti',
 'Samyuktha',
 'kriti',
 'Krishna',
 'Indira')

In [33]:
#QUESTION 4

In [34]:
#Creating a sets it_companies, A, B, age
it_companies = {'Facebook','Google','Microsoft','Apple','IBM','Oracle','Amazon'}
A = {19,22,24,20,25,26}
B = {19,22,20,25,26,24,28,27}
age = [22,19,24,25,26,24,25,24]

In [35]:
#Length of set it_companies
len(it_companies)

7

In [36]:
#Adding 'twitter' to set it_companies
it_companies.add("Twitter")
it_companies

{'Amazon',
 'Apple',
 'Facebook',
 'Google',
 'IBM',
 'Microsoft',
 'Oracle',
 'Twitter'}

In [37]:
#Insert mutliple values into a set
it_companies.update(['TCS','Wipro'])
it_companies

{'Amazon',
 'Apple',
 'Facebook',
 'Google',
 'IBM',
 'Microsoft',
 'Oracle',
 'TCS',
 'Twitter',
 'Wipro'}

In [38]:
#remove items from a set
it_companies.remove('Wipro')
it_companies

{'Amazon',
 'Apple',
 'Facebook',
 'Google',
 'IBM',
 'Microsoft',
 'Oracle',
 'TCS',
 'Twitter'}

In [39]:
it_companies.remove('MindTree')

KeyError: 'MindTree'

In [40]:
it_companies.discard('MindTree')

In [41]:
#Joining two sets
C = A.union(B) #Joins two sets A and B and also removes duplicate items
C

{19, 20, 22, 24, 25, 26, 27, 28}

In [42]:
#Intersecting two sets
D = A.intersection(B) #Intersection will results common items b/w the two sets A and B
D

{19, 20, 22, 24, 25, 26}

In [43]:
#Is A is subset of B
A.issubset(B) #issubset function checks if all items in A present in B, if true then A is subset of B otherwise not.

True

In [44]:
#are A and B disjoint sets
A.isdisjoint(B) #isdisjoint function checks if any item in set A present in B, if true not disjoint otherwise disjoint

False

In [45]:
#Insert one set items into another
A.update(B) #Insert items from set B into set A
A

{19, 20, 22, 24, 25, 26, 27, 28}

In [46]:
B.update(A) #Insert items from set A into setB
B

{19, 20, 22, 24, 25, 26, 27, 28}

In [47]:
#Symmetric difference between two sets A and B
A.symmetric_difference(B)

set()

In [48]:
#Deleting the sets completely
del A    #deletes the set A
del B    #deletes the set B
del it_companies #deletes the set it_companies

In [49]:
A

NameError: name 'A' is not defined

In [50]:
age

[22, 19, 24, 25, 26, 24, 25, 24]

In [51]:
#Converting a list age to a set
sage = set(age)
sage

{19, 22, 24, 25, 26}

In [52]:
#comparing the lengths of age and sage
len(age) == len(sage)

False

In [53]:
#QUESTION 5

In [54]:
#calculating area of circle
radius = 30
PI = 3.14
_area_of_circle = PI * radius * radius
_area_of_circle

2826.0

In [55]:
#calculating circumference of circle
_circum_of_circle = 2 * PI * radius
_circum_of_circle

188.4

In [56]:
#claculate area by taking radius as user Input
r = float(input("Enter radius"))   #reading input from user
area = PI * r * r   #formula to calculate area of circle
area

Enter radius30


2826.0

In [57]:
#QUESTION 6

In [58]:
#Unique words in a sentence
A = "I am a teacher and I love to inspire and teach people"
B = set(A.split(" ")) #First split() splits each word in a sentence and that will be stored in list.
#list will be converted into set using set() because set doesn't contain duplicate values
len(B)   #results no of unique words presents in the sentence

10

In [59]:
#QUESTION 7

In [60]:
#tab escaping sequence
print("Name\t\tAge\tCountry\tcity\nAsabench\t250\tFinland\tHelsinki") 
#\t creates tab space between the words
#\n to print words in new line

Name		Age	Country	city
Asabench	250	Finland	Helsinki


In [61]:
#QUESTION 8

In [62]:
#String formatting
radius = 10     # circle radius
area = 3.14 * radius ** 2      #formula to calculate area
print("radius = {radius}".format(radius = 10))
print("area = {PI} * radius **2 ".format(PI=3.14))
print("\"The area of a circle with radius {radius} is {area} meter square.\"".format(radius = 10, area = 3.14 * radius **2))

radius = 10
area = 3.14 * radius **2 
"The area of a circle with radius 10 is 314.0 meter square."


In [63]:
#QUESTION 9

In [65]:
lbs= []         #list for weight in lbs. 
n = int(input("Enter list size:"))  #Taking size of the list from the user 
for i in range(n):     #for loop to take input from the user
    ele = int(input("Enter weights(lbs) of N students")) #Taking the weight in lbs. from the user
    lbs.append(ele)  #appending the weights from the user to list lbs
kgs = [[]]*n    #List for weight in kgs
for i in range(n):
    kgs[i] = lbs[i]/2.2046 #calculating kgs for each weight and assigning them to kgs list with respective indexes
kgs     #printing the items in kgs list
    

Enter list size:4
Enter weights(lbs) of N students150
Enter weights(lbs) of N students155
Enter weights(lbs) of N students145
Enter weights(lbs) of N students148


[68.03955366052799, 70.30753878254558, 65.77156853851038, 67.13235961172094]

In [66]:
lbs

[150, 155, 145, 148]

In [67]:
kgs

[68.03955366052799, 70.30753878254558, 65.77156853851038, 67.13235961172094]

In [68]:
#QUESTION 10

In [69]:
import numpy as np 
#sklearn is a package where we find Machine Learning algorithms 
from sklearn.model_selection import train_test_split  #tran_test_split to split data
from sklearn.neighbors import KNeighborsClassifier    #To implement KNN
x = np.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]]) #Datasets obtained from the given graph
y = np.array([0,0,1,1,1,0,0,0]) #classes present at the respective data points
#splitting the data into two equal half. first half is for training and later is for testing
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.5, random_state = 0, shuffle = False)
print(x_train)  
print(y_train)
neighbor = KNeighborsClassifier(n_neighbors = 3)   #implementing KNN with k=3
neighbor.fit(x_train,y_train)       #fit the KNN from the training data
y_pred = neighbor.predict(x_test)   #predict the output for the data 
y_pred  #print the predictions 

[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]


array([1, 1, 1, 1])

In [70]:
from sklearn.metrics import confusion_matrix   #importing confusion matrix function from the sklearn package
confusion_matrix(y_test,y_pred) #comparing the testing class labels with predicted class labels

array([[0, 3],
       [0, 1]], dtype=int64)